language: go

go:
  - 1.7
  - 1.8
  - 1.9

before_install:
  - go get github.com/mattn/goveralls

script:
# lint
#  test
  - make build
  - go test -i $(go list ./... | grep -v /vendor)

notifications:
  email:
    on_success: never
    on_failure: never