language: go

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x

before_install:
  - go get -u github.com/haya14busa/goverage

script:
# lint
#  test
  - make build
  - goverage -v -coverprofile=coverage.txt -covermode=count .

notifications:
  email:
    on_success: never
    on_failure: never

after_success:
  - bash <(curl -s https://codecov.io/bash)
