language: go
sudo: required

services:
  - docker

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x

before_install:
  - go get -u github.com/haya14busa/goverage

script:
# lint
#  test
  - make build
  - ./testdata/test.sh

notifications:
  email:
    on_success: never
    on_failure: never

after_success:
  - bash <(curl -s https://codecov.io/bash)
